### ISSUE TITLE
Determine best way to trigger bin2tif extractor in CyVerse

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/openstack-terraform-nomad#10]
Meet with Tony to explore options & document results here in ticket

**Comment by Chris-Schnaufer** [comment]
Talk to Upendra

**Comment by julianpistorius** [comment]
See #11. 

> Things have changed. After discussions with Nirav, etc. there will be no 'trigger'.
> 
> The workflow will run the first extractor step after a step that has confirmed that the data for the processing batch/'packet' has been successfully transferred and staged.
> 
> I think this can be closed

**Comment by julianpistorius** [comment]
This should be closed.
