### ISSUE TITLE
Configure CyVerse trigger for running bin2tif extractor

### ISSUE THREAD

**Issue by Chris-Schnaufer** [az-digitalag/openstack-terraform-nomad#11]
Once the best approach is taken for starting the extractor, "make it so"

**Comment by julianpistorius** [comment]
Things have changed. After discussions with Nirav, etc. there will be no 'trigger'. 

The workflow will run the first extractor step after a step that has confirmed that the data for the processing batch/'packet' has been successfully transferred and staged.

I think this can be closed.

**Comment by julianpistorius** [comment]
This should be closed as well.
